#frontend  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-frontend
  labels:
    app: node-app-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-app-front
  template:
    metadata:
      name: frontend-Pod
      labels:
        app: node-app-front
    spec:  
       containers:  
        - name: frontend-container 
          image: image-registry.openshift-image-registry.svc:5000/dhanya-jenkins/node-gitclient:8
          imagePullPolicy: Always
          ports:
          - containerPort: 3000
          env:
          - name: REACT_APP_API_BASE_URL
            value: http://node-route-back-dhanya-jenkins.edge-dev-410-915b3b336cabec458a7c7ec2aa7c625f-0000.us-south.containers.appdomain.cloud
---
#frontend service
kind: Service
apiVersion: v1
metadata:
  name: node-service-frontend
  namespace: dhanya-jenkins
spec:
  type: ClusterIP
  ports:
    - name: targetss
      protocol: TCP
      port: 3000
      targetPort: 3000
  selector:
    app: node-app-front
---
#frontend route
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: node-route
  namespace: dhanya-jenkins
  labels:
        app: node-app-front
spec:
  to:
    kind: Service
    name: node-service-frontend
    weight: 100
  port:
    targetPort: targetss
